name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    if: ${{ vars.PUBLISH_NEW_IMAGE == 'true' }}
    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      uses: docker/login-action@v2.1.0
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: false
    - name: Build the Docker image
      run: docker build . --file front.Dockerfile --tag ddeer1109/bwell:frontend
    - name: Push to Dockerhub
      run: docker push ddeer1109/bwell:frontend

  
  sshDeploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ls -al
          bash /deploy.sh
          docker ps

  